services:
  see-containers:
    build:
      context: .
      dockerfile: Dockerfile
    image: rizkidn17/see-containers
    container_name: see-containers
    environment:
      - PORT=9090
    ports:
      - "3000:9090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped