services:
  see-containers:
    build:
      context: .
      dockerfile: Dockerfile
    image: rizkidn17/see-containers
    container_name: see-containers
    environment:
      - PORT=8080
    ports:
      - "3000:8080"
    restart: unless-stopped